### ISSUE TITLE
DbQueryStore not getting it.

### ISSUE THREAD

**Issue by KunalBurangi** [easyquery/AspNetCoreSamples#16]
I am trying to save and load query from my database table but the functions of Dbquerystore is not getting hit . i dont know what is the problem. the queries are getting stored and load from the local storage.

**Comment by antifree** [comment]
Hello,

What does it mean `local storage` in your case?

If we are talking about the browser`s local storage, you should use the enterprise edition of EasyQuery.JS (`eq.enterpise.min.js` in case using cdn or add `easyquery/enterpise ` in case using `npm`).  Do not forget to apply the license keys. You can find more information in this [article](https://korzh.com/easyquery/docs/getting-started/aspnet-core-razor).

If your query is saved to the file system instead of your database, you should check if you registered your store in EasyQuery options at the back-end.  You need to replace 
```c#
options.UseQueryStore(services => new FileQueryStore("App_Data"));
```

to 

```c#
options.UseQueryStore(services => new DbQueryStore(services));
```
